[workspace]
members = ["player-motion", "player-shooting", "player-bullets", "player-bullet-lifecycle", "early-gameplay"]
exclude = ["player-motion-openvm", "player-state-openvm", "player-shooting-openvm"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "GPL-3.0-only"
rust-version = "1.91.1"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
